name: Create Bats Test Env
description: Create Bats Test Env

inputs:
  perform_ockam_enroll:
    description: "Perform Ockam Enroll"
    required: true
  ockam_repository_ref:
    description: "Ref From Which To Run Bats Test"
    required: false
  ockam_cli_repository_ref:
    description: "Ref From Which To Build Ockam Command"
    required: false
  controller_id:
    description: "Controller ID Of Ockam Command"
    required: false
  controller_addr:
    description: "Controller Address Of Ockam Command"
    required: false
  build_ockam_binary:
    description: "Build Ockam Binary"
    required: true
    default: "true"
  script_path:
    description: "Enrollment Script Path"
    required: true
  email_address:
    description: "Emaill Address To Run Ockam Enroll"
    required: false
    default: "test@ockam.io"
  docker_image:
    description: "Docker Image To Run Ockam Enroll"
    required: false
    default: "ghcr.io/build-trust/artifacts-helper:latest"
  ockam_identity:
    description: "Ockam Identity To Use For Enrollment"
    required: false

runs:
  using: "composite"

  steps:
    - name: Check If Nix Is Installed
      id: nix-status
      shell: bash
      run: |
        if ! which nix; then
          echo "NIX_STATUS=1"  >> $GITHUB_ENV
        fi

    - name: Install Nix If There Is No Cache
      if: ${{ env.NIX_STATUS == 1 }}
      shell: bash
      run: |
        curl -L https://nixos.org/nix/install | sh -s -- --daemon
        sudo echo "extra-experimental-features = flakes" >> /etc/nix/nix.conf || echo "extra-experimental-features = flakes"
        sudo echo "extra-experimental-features = nix-command" >> /etc/nix/nix.conf || echo "extra-experimental-features = nix-command" >> /etc/nix/nix.conf

        echo "/nix/var/nix/profiles/per-user/root/profile/bin" >> $GITHUB_PATH
        echo "/nix/var/nix/profiles/default/bin" >> $GITHUB_PATH

    - shell: bash
      run: |
        echo "OCKAM_DISABLE_UPGRADE_CHECK=1"  >> $GITHUB_ENV
        echo "====> ${{ inputs.ockam_repository_ref }} Ockam ref here"
        if [[ -n "${{ inputs.controller_id }}" ]]; then
          echo "OCKAM_CONTROLLER_IDENTITY_ID=${{ inputs.controller_id }}" >> $GITHUB_ENV
          echo "OCKAM_CONTROLLER_ADDR=${{ inputs.controller_addr }}" >> $GITHUB_ENV
        fi

    - if: ${{ inputs.perform_ockam_enroll == 'false' }}
      shell: bash
      run: |
        set -ex
        mkdir /github/home/.local
        cp -r /configs/.ockam /github/home

        ls /github/home

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ inputs.ockam_cli_repository_ref != '' && inputs.ockam_cli_repository_ref || inputs.ockam_repository_ref }}
        repository: build-trust/ockam
        path: ockam_cli

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ inputs.ockam_repository_ref }}
        repository: build-trust/ockam
        path: ockam_bats

    - if: ${{ inputs.build_ockam_binary == 'true' }}
      uses: dtolnay/rust-toolchain@stable

    - if: ${{ inputs.build_ockam_binary == 'true' }}
      uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0
      with:
        workspaces: "ockam_cli -> target"
        cache-on-failure: "true"

    - name: Nix Collect Garbage
      shell: bash
      run: nix-collect-garbage

    - if: ${{ inputs.build_ockam_binary == 'true' }}
      shell: bash
      working-directory: ockam_cli
      run: |
        set -ex
        echo $OCKAM_DISABLE_UPGRADE_CHECK

        if which docker; then
          cargo install --version 0.2.5 cross
          CROSS_REMOTE=1 CROSS_REMOTE_COPY_CACHE=1 cross build --locked --bin ockam --target x86_64-unknown-linux-musl
          echo "PATH=$PATH:$(pwd)/target/x86_64-unknown-linux-musl/debug" >> $GITHUB_ENV
        else

          nix --quiet develop ./tools/nix#rust --command cargo build --locked --bin ockam
          mv ./target/debug/ockam /usr/bin
        fi

    # - if: ${{ inputs.build_ockam_binary == 'true' }}
    #   shell: bash
    #   working-directory: ockam_cli
    #   run: |
    #     echo "PATH=$PATH:$(pwd)/target/x86_64-unknown-linux-musl/debug" >> $GITHUB_ENV
    #     echo "NIXPKGS_ALLOW_UNFREE=1" >> $GITHUB_ENV

    - shell: bash
      if: ${{ inputs.perform_ockam_enroll == 'true' }}
      run: |
        # Get enrollment code
        set -ex
        # export QUIET=1
        export OCKAM_LOGGING=0
        export OCKAM_OPENTELEMETRY_EXPORT=0
        export OCKAM_DEFAULT_TIMEOUT=10m
        
        mkdir -p ~/.ockam
        export OCKAM_HOME=~/.ockam
        echo "OCKAM_HOME=$OCKAM_HOME"
        ockam identity import ${{ inputs.ockam_identity }}
        echo "OCKAM_ENROLL_LOG=$OCKAM_HOME" >> $GITHUB_ENV

    - shell: bash
      run: |
        UUID=$(openssl rand -hex 8)
        echo "UNIQUE_ID=$UUID" >> $GITHUB_ENV

    - if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.run_id }}-ockam-enroll-logs-${{ inputs.controller_addr == '' && 'prod' || 'dev' }}-${{ inputs.perform_ockam_enroll == 'true' && 'new_enroll' || 'cached_enroll' }}-${{ steps.set-output-job-id.outputs.job_id }}-${{ env.UNIQUE_ID }}
        path: ${{ env.OCKAM_ENROLL_LOG }}

    - shell: bash
      run: |
        set -ex
        ockam space list --output json
        ockam project show
        ockam project ticket
