name: Cancel Workflow
description: Cancel A Running Workflow

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        script: |
          console.log('Cancelling ...');
          github.rest.actions.cancelWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          })

    - shell: bash
      run: sleep 60
