name: Verify Image Signature
description: Verify Image Signature
inputs:
  cosign_pub_key:
    description: "Cosign public key"
    required: true
  image:
    description: "Docker image"
    required: true

runs:
  using: "composite"
  steps:
    - uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4

    - shell: bash
      env:
        PUB_KEY: '${{ inputs.cosign_pub_key }}'
      run: |
        if cosign verify --key env://PUB_KEY ${{ inputs.image }} --yes; then
          echo "Signature verified"
        else
          echo "Invalid signature"
          exit 1
        fi
